### ISSUE TITLE
How to pass ReactApplication to native modules?

### ISSUE THREAD

**Issue by thevolcanomanishere** [petterh/react-europe-demo#12]
Hi Peter,

This repo has been a great help in integrating a react-native project as a lib so thanks!

Some native modules (that you add with .addPackage()) require that you pass a ReactApplication param when you add them. I have tried implementing ReactApplication in the ReactNativeDemoLibrary class but that requires a bunch of methods that seem to conflict with the  ReactInstanceManager.builder() methods.

CodePush and Sentry are examples of packages that require ReactApplication as a param.

Thanks! @petterh

**Comment by petterh** [comment]
Hi,

Late to the party.

Near as I can tell, the constructor for the `CodePush` package requires a `Context` as its second parameter, while the constructor for `RNSentryPackage` doesn't require anything at all. Or am I missing something? (Things may have changed since you posted this question.)

**Comment by petterh** [comment]
See also [this project](https://github.com/petterh/react-native-android-activity) for a different take on this.
