### ISSUE TITLE
Support for Gradle 3.1.4 replacing dependency compile with implementation or api

### ISSUE THREAD

**Issue by devpascoe** [petterh/react-europe-demo#13]
Such a life saver of a code sample here, thanks again.
Essentially just trying to update it to use latest build tools and gradle. Having an issue with reactnativedemolibrary/build.gradle
Its dependencies reference 'com.facebook.react:react-native:0.55.4' (well i'm using 0.55.4) but instead of the keyword compile, gradle 3 looks like it needs either implementation or api.

Issue is in HostApp1 or 2 the whole react-native classes don't seem to be carried across. I can specify a reference to them in HostApp1's build.gradle and it will work.  eg,
implementation 'com.contoso.react:reactnativedemolibrary:0.2.0'
implementation 'com.facebook.react:react-native:+' // <-- i added this

Or i can replace the reactnativedemolibrary/build.gradle back to using the "compile" keyword and it will work (with warning messages).

I've tried all kinds of combinations of "implementation" or "api". Be great to not have to either specify react native also in the HostApp1 gradle or remain using the older version of gradle for builds.

Cheers

**Comment by petterh** [comment]
I have upgraded to React Native 0.60.5 and the latest Gradle wrapper and plugin versions, and pretty much everything else. This was not entirely trivial, so I understand your frustration. Things should work out of the box now; if they don't, feel free to reopen the issue.
